# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup NodeJS LTS
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm ci
      
      - name: Install Angular CLI
        run: npm i -g @angular/cli
      
      - name: Setup Git
        run: git config user.email "garrett@orlandoiot.com"
        
      - name: Setup Git
        run: git config user.name "Github Actions Runner"
      
      - name: Deploy site
        run: ng deploy --cname=orlandoiot.com --no-silent --name=gomjabar6
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_GH_PAGES_TOKEN }}
